name = "gemini-ai-chat"
main = "./_worker.js"
compatibility_date = "2024-05-05"

kv_namespaces = [
  { binding = "IMAGES", id = "your-kv-namespace-id", preview_id = "your-kv-namespace-preview-id" }
]

[site]
bucket = "./_static"